### ISSUE TITLE
YamlEncoder.dump doesn't handle DateTime (or Date) properly

### ISSUE THREAD

**Issue by joeyfreund** [xnlogic/pacer#77]
```ruby
jruby-1.7.18 :040 > Pacer::YamlEncoder.encode_property [Time.new, DateTime.new, Date.new]
 => " ---\n- 2015-05-13 12:23:42.625000000 -04:00\n- !ruby/object:DateTime '-4713-12-31 18:42:28.000000000 -05:17'\n- -4712-01-01\n"
```

Notice that the values are all wrong for `DateTime` and `Date`.

_Important:_ This is __not__ a bug in Pacer, it is a bug in the YAML library. We'll just have to find a workaround (or see if this bug has been fixed in a more recent version of the YAML library).

**Comment by pangloss** [comment]
I think we can just say we don't support dates in data structures

**Comment by pangloss** [comment]
Also:  

`DateTime.new #=> #<DateTime: -4712-01-01T00:00:00+00:00 ((0j,0s,0n),+0s,2299161j)>` 
vs
 `DateTime.now #=> #<DateTime: 2015-05-13T15:58:08-04:00 ((2457156j,71888s,911297000n), -14400s,2299161j)>`

**Comment by joeyfreund** [comment]
Oh Ruby ... you'll never stop tricking me.
